import cafeterabialetti from "./Assets/cafeterabialetti.jpg";
import cafeterabialetti6 from "./Assets/cafeterabialetti6.jpg";
import cafeterabialettir from "./Assets/cafeterabialettir.jpg";
import hudsonsarten from "./Assets/sarten-hudson.jpg";
import cacerolahudson from "./Assets/cacehudson.jpg";
import moldehudson from "./Assets/moldehudson.jpg";
import utenhudson from "./Assets/utenhudson.jpg";
import batidorakit from "./Assets/batidorakit.jpg";
import cafkita from "./Assets/cafetera-kitchen.jpg";
import mantelmic from "./Assets/mantelmic.jpg";
import mantelnatmic from "./Assets/mantelnatmic.jpg";
import mantelindivmica from "./Assets/mantelindvmic.jpg";
import termostanley from "./Assets/termostan.jpg";
import matestanley from "./Assets/Mate-Verde.jpg";
import moldepyrex from "./Assets/molde-desmontable-teflon-pyrex-26cm.jpg";
import sartpyrex from "./Assets/sartenpyrex.jpg";
import tazastsuji from "./Assets/descarga.jpg";
import vajillatsuji from "./Assets/porcelanatsuji.jpg";
import vajillapark from "./Assets/parkdesignvaji.jpg";
import platopark from "./Assets/platopark.jpg";
import polywoodtramontina from "./Assets/cub1.jpg";
import amazonastramontina from "./Assets/amazonas.png";
import tragolargonadir from "./Assets/vasoslargosnadir.jpg";
import champagnenadir from "./Assets/champagnenadir.jpg";
import espatulayporcitomorrow from "./Assets/espatulatomorrow.jpg";
import ralladorzestertomorrow from "./Assets/ralladortomorrow.jpg";
import copavinolibbey from "./Assets/vinolibbey.jpg";
import copavinodiamantlibbey from "./Assets/copa.jpg";
export const products = [
    {
        id: 1,
        titulo: "Cafetera Bialetti Moka Express 18 pocillos",
        categoria: "cafe y te",
        precio: "21899.00",
        marca: "Bialetti",
        descripcion:"Con el Bialetti moka, el placer de tomar un café se convierte en un ritual diario. Su investigación en los mejores materiales garantiza un resultado eficiente, combinando un diseño refinado con el respeto por el sabor del mejor café tradicional. Material: Acero Capacidad: 18 pocillos.",
        codigo:"bia18p",
        stock:15,
        image:cafeterabialetti,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 2,
        titulo: "Cafetera Bialetti Class Acero 6 pocillos",
        categoria: "cafe y te",
        precio: "11880.00",
        marca: "Bialetti",
        descripcion:"Las mejores cafeteras italianas -Material: Acero -Apta cocina inducción -Capacidad: 6 pocillos",
        codigo:"bia6p",
        stock:10,
        image:cafeterabialetti6,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 3,
        titulo: "Cafetera Bialetti Rainbow 6 Tazas",
        categoria: "cafe y te",
        precio: "10799.00",
        marca: "Bialetti",
        descripcion:"Cafetera Rainbow Bialetti en aluminio con manija y mango en baquelita.",
        codigo:"biar6t",
        stock:5,
        image:cafeterabialettir,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 4,
        titulo: "Sartén Cerámica Apta Inducción Hudson",
        categoria: "ollas y sartenes",
        precio: "2679.00",
        marca: "Hudson",
        descripcion:"Sartén 24 cm de aluminio forjado con revestimiento cerámico y doble antiadherente.",
        codigo:"hudsart",
        stock:2,
        image:hudsonsarten,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 5,
        titulo: "Cacerola Cerámica Apta Inducción Hudson",
        categoria: "ollas y sartenes",
        precio: "4449.00",
        marca: "Hudson",
        descripcion:"Cacerola 24 cm con revestimiento cerámico y doble antiadherente.",
        codigo:"hudcacer",
        stock:2,
        image:cacerolahudson,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 6,
        titulo: "Molde para Torta Desmontable  Hudson",
        categoria: "reposteria",
        precio: "1099.00",
        marca: "Hudson",
        descripcion:"Molde para torta desmontable 24 cm con revestimiento cerámico y doble antiadherente.",
        codigo:"hudmold",
        stock:12,
        image:moldehudson,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 7,
        titulo: "Set de 6 Utensilios De Nylon y Acero Hudson",
        categoria: "utensilios",
        precio: "3269.00",
        marca: "Hudson",
        descripcion:"Set de 6 Utensilios De Nylon Color Gris. Mango Acero Inoxidable. Con Base Colgante. Ideal para Teflón o Cerámica",
        codigo:"huduten",
        stock:8,
        image:utenhudson,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 8,
        titulo: "Batidora de Pie Artisan 4,8 Lts Roja KitchenAid",
        categoria: "reposteria",
        precio: "52599.00",
        marca: "KitchenAid",
        descripcion:"Su potencia es de 300W. Permite una mayor precisión para obtener mezclas perfectas. Según la receta podrás regular la velocidad en 10 velocidades diferentes logrando desde un suave mezclado hasta un intenso batido. Su bowl de 4.8 litros permite ser utilizado de una forma muy versátil, preparando tanto pequeñas como grandes cantidades según la receta.",
        codigo:"kitabat",
        stock:5,
        image:batidorakit,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 9,
        titulo: "Cafetera Francesa Digital KitchenAid",
        categoria: "cafe y te",
        precio: "33999.00",
        marca: "KitchenAid",
        descripcion:"Cafetera Kitchenaid Prensa Precisión Inalámbrica Pantalla Lcd.",
        codigo:"kitacaf",
        stock:4,
        image:cafkita,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 10,
        titulo: "Mantel de hojas 140 x 240 cm Mica",
        categoria: "manteleria",
        precio: "3890.00",
        marca: "Mica",
        descripcion:"Marca: Mica Modelo: MANTEL ECOCUE Tipo: manteles Forma: rectangular Material: ecocuero",
        codigo:"mantmic",
        stock:6,
        image:mantelmic,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 11,
        titulo: "Mantel de mesa Natural 200 x 150cm Mica",
        categoria: "manteleria",
        precio: "3890.00",
        marca: "Mica",
        descripcion:"Modelo: NATURAL 200X150 Tipo: manteles Forma: rectangular Material: algodón Ancho/Diámetro: 150 cm Largo: 200 cm Origen: Argentina",
        codigo:"mantnatmic",
        stock:6,
        image:mantelnatmic,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 12,
        titulo: "Individual modelo Inccactus 38cm Mica",
        categoria: "manteleria",
        precio: "459.00",
        marca: "Mica",
        descripcion:"Modelo: INCCACTUS Tipo: Individuales Forma: redonda Material: Goma Diámetro: 38 cm Origen: China",
        codigo:"mantindmic",
        stock:6,
        image:mantelindivmica,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 13,
        titulo: "Termo Clásico Stanley 1,9 lts Verde",
        categoria: "termos y mates",
        precio: "12500.00",
        marca: "Stanley",
        descripcion:"Mantiene frío por 48 hs y calor por 45 hs.Tapa con aislamiento térmico de 236ml para usar como taza.",
        codigo:"termstan",
        stock:13,
        image:termostanley,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 14,
        titulo: "Mate Clásico Stanley 236 mls Verde",
        categoria: "termos y mates",
        precio: "6090.00",
        marca: "Stanley",
        descripcion:"Mate Stanley 236 ml 30min Caliente 3h Frio Térmico. Mantiene la temperatura durante toda la cebada.",
        codigo:"matstan",
        stock:14,
        image:matestanley,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 15,
        titulo: "Molde Torta Desmontable de Teflón Pyrex 26 cm",
        categoria: "reposteria",
        precio: "1165.00",
        marca: "Pyrex",
        descripcion:"Molde metálico redondo desmontable para torta. Medidas: 25,4  x 6,98 cm. Antiadherente de primera calidad",
        codigo:"moldpyrex",
        stock:8,
        image:moldepyrex,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 16,
        titulo: "Sarten 26 Cm Pyrex Fuego Antiadherente",
        categoria: "ollas y sartenes",
        precio: "3147.00",
        marca: "Pyrex",
        descripcion:"Este sartén tiene el tamaño ideal para cocinar huevos estrellados, nada se le pega por su recubrimiento antiadherente y es fácil de manipular por su mango ergonómico suave al tacto. Su recubrimiento ayuda a cocinar saludablemente, ya que requiere de menos aceite para cocinar los alimentos.",
        codigo:"sartpyrex",
        stock:8,
        image:sartpyrex,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 17,
        titulo: "Set X6 Tazas De Té Con Platos Porcelana Tsuji",
        categoria: "cafe y te",
        precio: "3147.00",
        marca: "Porcelana Tsuji",
        descripcion:"Líneas puras y limpias con formas suaves y una sencilla elegancia, dan una gran versatilidad a estas piezas.",
        codigo:"tazastsuji",
        stock:4,
        image:tazastsuji,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 18,
        titulo: "Set De Vajilla 16 Piezas Rustic Porcelana Tsuji",
        categoria: "vajilla",
        precio: "12010.00",
        marca: "Porcelana Tsuji",
        descripcion:"Una textura abstracta en tonos ocre contrasta con un celeste calmo en los bordes de las piezas. Cantidad de piezas: 16 unidades. El set está compuesto por: - 4 Platos Playos (25,5 cm) - 4 Platos Postre (20 cm) - 4 Platos Hondos (20,7cm )",
        codigo:"vajillatsuji",
        stock:5,
        image:vajillatsuji,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 19,
        titulo: "Set De Vajilla De Melamina 16 piezas Park Design",
        categoria: "vajilla",
        precio: "8700.00",
        marca: "Park Design",
        descripcion:"Set de vajilla de melamina 16 piezas: - Plato Playo redondo: 26,5cm (por 4 unidades) - Bowl: 19,5cm de diametro (por 4 unidades) - Plato de  postre: 21,5 cm (por 4 unidades) - Plato de pan: 16,5cm (por 4 unidades)",
        codigo:"vajillapark",
        stock:5,
        image:vajillapark,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 20,
        titulo: "Plato Playo De Melamina X4 Unidades Park Design",
        categoria: "vajilla",
        precio: "3500.00",
        marca: "Park Design",
        descripcion:"Plato Playo redondo: 26cm x 4 Unidades Material: Melamina Colores: Blanco con Gris terminación opaca",
        codigo:"platopark",
        stock:5,
        image:platopark,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 21,
        titulo: "Cubiertos Polywood 24 piezas Tramontina",
        categoria: "cubiertos",
        precio: "6260.00",
        marca: "Tramontina",
        descripcion:"La línea Polywood tienen láminas de acero inoxidable con formato y espesor que garantizan la resistencia y evitan deformaciones.",
        codigo:"cubpolytramon",
        stock:5,
        image:polywoodtramontina,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 22,
        titulo: "Cubiertos Amazonas 24 piezas Tramontina",
        categoria: "cubiertos",
        precio: "5472.00",
        marca: "Tramontina",
        descripcion:"Juego de cubiertos x24 piezas de Acero inoxidable. Cubiertos forjados y templados, con mayor poder de corte. Estilo, equilibrio y peso. Muy resistentes a la corrosión y fáciles de limpiar. Son aptos lavavajillas.",
        codigo:"cubamaztramon",
        stock:5,
        image:amazonastramontina,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 23,
        titulo: "Set de 6 Vasos De Vidrio Nadir Bristol Trago Largo",
        categoria: "vasos y copas",
        precio: "2472.00",
        marca: "Nadir Argentina",
        descripcion:"6 Vasos para Trago Largo Nadir Barone 340 ml de capacidad.",
        codigo:"traglargnadir",
        stock:5,
        image:tragolargonadir,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 24,
        titulo: "Set de 6 Copas de Champagne Nadir Barone",
        categoria: "vasos y copas",
        precio: "3472.00",
        marca: "Nadir Argentina",
        descripcion:"6 copas de Champagne Vidrio Nadir Barone 190 ml. de capacidad",
        codigo:"champnadir",
        stock:5,
        image:champagnenadir,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 25,
        titulo: "Espátula y porcionador de torta Tomorrow's Kitchen",
        categoria: "utensilios",
        precio: "1780.00",
        marca: "Tomorrow´s Kitchen",
        descripcion:"Cake Server Divider es una herramienta  diseñada para dividir, cortar y servir un pastel en poco tiempo. Guardado en el mango, el divisor le permite dividir su pastel en 8, 10 o 12 piezas.",
        codigo:"espatulatomorrow",
        stock:8,
        image:espatulayporcitomorrow,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 26,
        titulo: "Rallador + Zester para cítricos Tomorrow's  Kitchen",
        categoria: "utensilios",
        precio: "1675.00",
        marca: "Tomorrow´s Kitchen",
        descripcion:"El rallador de cítricos + pelador de Tomorrow Kitchen es una herramienta diseñada para rallar cítricos y para cortar la cáscara.",
        codigo:"ralladortomorrow",
        stock:8,
        image:ralladorzestertomorrow,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 27,
        titulo: "Vaso Vino Stemless Libbey 451 Ml X6 Unidades",
        categoria: "vasos y copas",
        precio: "2589.00",
        marca: "Libbey",
        descripcion:"Copa para Vino Sin Pie Stemless X6 Unidades 451 ml. de capacidad.",
        codigo:"copvinolibbey",
        stock:7,
        image:copavinolibbey,
        cantidad:1,
        ptotal:0,
      },
      {
        id: 28,
        titulo: "Copa Vino Diamante 490 Ml x6 Libey",
        categoria: "vasos y copas",
        precio: "1549.00",
        marca: "Libbey",
        descripcion:"Copa de Degustación para Vino - Forma Diamante 490 Ml x6 unidades",
        codigo:"copavinolibbey",
        stock:0,
        image:copavinodiamantlibbey,
        cantidad:1,
        ptotal:0,

      }
]