import cafeterabialetti from "./Productos/Assets/cafeterabialetti.jpg";
import cafeterabialetti6 from "./Productos/Assets/cafeterabialetti6.jpg";
import cafeterabialettir from "./Productos/Assets/cafeterabialettir.jpg";
import hudsonsarten from "./Productos/Assets/sarten-hudson.jpg";
import cacerolahudson from "./Productos/Assets/cacehudson.webp";
import moldehudson from "./Productos/Assets/moldehudson.jpg";
import utenhudson from "./Productos/Assets/utenhudson.jpg";
import batidorakit from "./Productos/Assets/batidorakit.jpg";
import cafkita from "./Productos/Assets/cafetera-kitchen.jpg";
import mantelmic from "./Productos/Assets/mantelmic.jpg";
import mantelnatmic from "./Productos/Assets/mantelnatmic.jpg";
import mantelindivmica from "./Productos/Assets/mantelindvmic.jpg";
import termostanley from "./Productos/Assets/termostan.jpg";
import matestanley from "./Productos/Assets/Mate-Verde.jpg";
export const PedidosAdmin = [
{
    id:444444,
    nropedido:444444,
    fecha:"04/05/2021",
    preciototal:76975.00,
    direccion: "Avenida Córdoba 225",
    productos:[
        {
            id: 1,
            titulo: "Cafetera Bialetti Moka Express 18 pocillos",
            categoria: "cafe y te",
            precio: "21899.00",
            marca: "Bialetti",
            descripcion:"Con el Bialetti moka, el placer de tomar un café se convierte en un ritual diario. Su investigación en los mejores materiales garantiza un resultado eficiente, combinando un diseño refinado con el respeto por el sabor del mejor café tradicional. Material: Acero Capacidad: 18 pocillos.",
            codigo:"bia18p",
            stock:15,
            image:cafeterabialetti,
            cantidad:1,
            ptotal:21899.00,
          },
          {
            id: 2,
            titulo: "Cafetera Bialetti Class Acero 6 pocillos",
            categoria: "cafe y te",
            precio: "11880.00",
            marca: "Bialetti",
            descripcion:"Las mejores cafeteras italianas -Material: Acero -Apta cocina inducción -Capacidad: 6 pocillos",
            codigo:"bia6p",
            stock:10,
            image:cafeterabialetti6,
            cantidad:1,
            ptotal:11880.00,
          },
          {
            id: 3,
            titulo: "Cafetera Bialetti Rainbow 6 Tazas",
            categoria: "cafe y te",
            precio: "10799.00",
            marca: "Bialetti",
            descripcion:"Cafetera Rainbow Bialetti en aluminio con manija y mango en baquelita.",
            codigo:"biar6t",
            stock:5,
            image:cafeterabialettir,
            cantidad:4,
            ptotal:43196.00,
          },
    ],
    nombre_persona:"Marcelo",
    apellido_persona:"Riviera",
},
{
    id:444443,
    nropedido:444443,
    fecha:"03/05/2021",
    preciototal:11496.00,
    direccion: "Avenida San Juan 210",
    productos:[
        {
            id: 4,
            titulo: "Sartén Cerámica Apta Inducción Hudson",
            categoria: "ollas y sartenes",
            precio: "2679.00",
            marca: "Hudson",
            descripcion:"Sartén 24 cm de aluminio forjado con revestimiento cerámico y doble antiadherente.",
            codigo:"hudsart",
            stock:2,
            image:hudsonsarten,
            cantidad:1,
            ptotal:2679.00,
          },
          {
            id: 5,
            titulo: "Cacerola Cerámica Apta Inducción Hudson",
            categoria: "ollas y sartenes",
            precio: "4449.00",
            marca: "Hudson",
            descripcion:"Cacerola 24 cm con revestimiento cerámico y doble antiadherente.",
            codigo:"hudcacer",
            stock:2,
            image:cacerolahudson,
            cantidad:1,
            ptotal:4449.00,
          },
          {
            id: 6,
            titulo: "Molde para Torta Desmontable  Hudson",
            categoria: "reposteria",
            precio: "1099.00",
            marca: "Hudson",
            descripcion:"Molde para torta desmontable 24 cm con revestimiento cerámico y doble antiadherente.",
            codigo:"hudmold",
            stock:12,
            image:moldehudson,
            cantidad:1,
            ptotal:1099.00,
          },
          {
            id: 7,
            titulo: "Set de 6 Utensilios De Nylon y Acero Hudson",
            categoria: "utensilios",
            precio: "3269.00",
            marca: "Hudson",
            descripcion:"Set de 6 Utensilios De Nylon Color Gris. Mango Acero Inoxidable. Con Base Colgante. Ideal para Teflón o Cerámica",
            codigo:"huduten",
            stock:8,
            image:utenhudson,
            cantidad:1,
            ptotal:3269.00,
          },
    ],
    nombre_persona:"Javier",
    apellido_persona:"Fontana",
},
{
    id:444442,
    nropedido:444442,
    fecha:"02/05/2021",
    preciototal:113427.00,
    direccion: "Rincón 421",
    productos:[
        {
            id: 8,
            titulo: "Batidora de Pie Artisan 4,8 Lts Roja KitchenAid",
            categoria: "reposteria",
            precio: "52599.00",
            marca: "KitchenAid",
            descripcion:"Su potencia es de 300W. Permite una mayor precisión para obtener mezclas perfectas. Según la receta podrás regular la velocidad en 10 velocidades diferentes logrando desde un suave mezclado hasta un intenso batido. Su bowl de 4.8 litros permite ser utilizado de una forma muy versátil, preparando tanto pequeñas como grandes cantidades según la receta.",
            codigo:"kitabat",
            stock:5,
            image:batidorakit,
            cantidad:1,
            ptotal:52599.00,
          },
          {
            id: 9,
            titulo: "Cafetera Francesa Digital KitchenAid",
            categoria: "cafe y te",
            precio: "33999.00",
            marca: "KitchenAid",
            descripcion:"Cafetera Kitchenaid Prensa Precisión Inalámbrica Pantalla Lcd.",
            codigo:"kitacaf",
            stock:4,
            image:cafkita,
            cantidad:1,
            ptotal:33999.00,
          },
          {
            id: 10,
            titulo: "Mantel de hojas 140 x 240 cm Mica",
            categoria: "manteleria",
            precio: "3890.00",
            marca: "Mica",
            descripcion:"Marca: Mica Modelo: MANTEL ECOCUE Tipo: manteles Forma: rectangular Material: ecocuero",
            codigo:"mantmic",
            stock:6,
            image:mantelmic,
            cantidad:1,
            ptotal:3890.00,
          },
          {
            id: 11,
            titulo: "Mantel de mesa Natural 200 x 150cm Mica",
            categoria: "manteleria",
            precio: "3890.00",
            marca: "Mica",
            descripcion:"Modelo: NATURAL 200X150 Tipo: manteles Forma: rectangular Material: algodón Ancho/Diámetro: 150 cm Largo: 200 cm Origen: Argentina",
            codigo:"mantnatmic",
            stock:6,
            image:mantelnatmic,
            cantidad:1,
            ptotal:3890.00,
          },
          {
            id: 12,
            titulo: "Individual modelo Inccactus 38cm Mica",
            categoria: "manteleria",
            precio: "459.00",
            marca: "Mica",
            descripcion:"Modelo: INCCACTUS Tipo: Individuales Forma: redonda Material: Goma Diámetro: 38 cm Origen: China",
            codigo:"mantindmic",
            stock:6,
            image:mantelindivmica,
            cantidad:1,
            ptotal:459.00,
          },
          {
            id: 13,
            titulo: "Termo Clásico Stanley 1,9 lts Verde",
            categoria: "termos y mates",
            precio: "12500.00",
            marca: "Stanley",
            descripcion:"Mantiene frío por 48 hs y calor por 45 hs.Tapa con aislamiento térmico de 236ml para usar como taza.",
            codigo:"termstan",
            stock:13,
            image:termostanley,
            cantidad:1,
            ptotal:12500.00,
          },
          {
            id: 14,
            titulo: "Mate Clásico Stanley 236 mls Verde",
            categoria: "termos y mates",
            precio: "6090.00",
            marca: "Stanley",
            descripcion:"Mate Stanley 236 ml 30min Caliente 3h Frio Térmico. Mantiene la temperatura durante toda la cebada.",
            codigo:"matstan",
            stock:14,
            image:matestanley,
            cantidad:1,
            ptotal:6090.00,
          },
    ],
    nombre_persona:"María",
    apellido_persona:"Carrascal",
},
]